language: javascript
addons:
  sauce_connect: true
rvm:
  - 1.9.3
env:
  global:
  - secure: c8gKLLfmM0TQCotSTXwVnFZcunyg0ApxXvLgWzgUQIXB4KkZVkPn5D5HnwDOkNHS2tCNcpiRj56mhtvHHot5YJOOvS5Gnp5cPk7SUUXUAgFbyq/44vpEXi9pYMCZa4bkY5ukZgz40wwr0ooiePxf0NAIFk0aiAxkQoTwOwEzHt2k8E6vXTX2pLIok2lYUSL6ZcgyNls/0iLZiQ8unezhfTW6t+E+6kM4P46FMUA5A0rfpK+qtbZ1SjIb3HwCP0qtOfP4m+StA1vb+LYpnW1E0PgRj231hJMrk/9sqIpQN+tbjk4nFg2P8sHLr/s2XpA/bebekhFVB6ZkCBXwAdhy8Q3Z5HvL9/X9Wd+zvNCKrZBsNAT3bixWlEKyJYtwONkujUPbgU3gXsZ+TWH4Hfq0F55Tgz4TJNlgOzWSm9kfInpxpLvi1i84x4f6w/ffIlS7L6HDkjAvD/jPdRA66MSQYyn7Magwd+YouJ3GbX7dr0iDS9LlIyWlYwkmrwQGDVXiD22+tuRudzTRQ8OxEZUPAwe4NiFF1o8zSdTo2eznqWo5j2+dIhAKkp8gzbmHKf1xzQZjtZvHCpvvysuadhdp1WU9aopA5kopfMxeSm3Qz1VNTSOXOJFJGelU0df1P/wtL8NHvMXr80eVJFGF6nIY1kFvkf+/QG/qQc8V3xkJW9g=
  - secure: LVOfNUyvT6ZJDADbyFP8w1MdZ9heZQAsEzIs6m6d1vA7pFGSmToq2HbHlyAGRQCgN2xp9gAadzdBw/PUIP4EuJTE04XylZ0KPIGTda8AcvUrLcJmNj5XktlAP69SxtmOzobSzzjKhHWpOdU3RCiK6VUJelUA26caoy+y2enPKjgHDjMUhJ1CZ52vxOl8yU6nzo85qo635NDhF35bxXlKs7PFYG1+NI9qHEJAY37Uf8RTw4p6QG4tO2j73C5fZR7p9yIsTpPRl1prXzEqBoB7wd1305MusXfFjNkCnU9b8x65uvvr2QoQCKw3rM98zcLV7dDfvDDLDgIRGsY4emkWeASbEEGQVjSviX+GjXjg/9wItAYnXLLm6NEq36LkxoBO2J6k331qzVDaAfYfpcu8a/TGGlo9GwUx9hb8qMF9KVTHAlv+dKzu9pOuud5yt+SmdKBzEJPUdAjM2TCy71MZ1/pL3IXiqUyue3nKY2g5DfoKzKpLBTRjoe4OEr9aUkFCUXk2120YkTzT6UtPMNvD+qZN0HHGkIliarVoK37SABgi3QABG2u76Ruj//SkoVPtJs3ltDi81W92lRgMqrbc2NTy0RT+mrupUlM0ToH8bE3J095ujkprDnwTaRFCgfqXMJt4mysKxK8szS0vF+yllj1m+/z3HnyhRYL0HKtofzQ=
before_script:
- npm install
before_install:
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- sudo rm -rf /usr/local/phantomjs/bin/phantomjs
- sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
install: travis_retry npm install
after_success:
- npm run ci
- npm run coveralls
